version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: service1/Dockerfile
    ports:
      - "8000:8000"  # FastAPI port
      - "50051:50051"  # gRPC port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  service2:
    build:
      context: .
      dockerfile: service2/Dockerfile
    ports:
      - "8001:8001"  # FastAPI port
    depends_on:
      service1:
        condition: service_healthy

