version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=blog.settings
      - DATABASE_URL=mysql://bloguser:blogpassword@db:3306/blogdb
      - REDIS_URL=redis://redis:6379/0

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mariadb_data:
  media_volume: 